cc_library(
    name = "screen",
    srcs = ["Screen.cc"],
    hdrs = ["Screen.h"],
    visibility = ["//visibility:public"],
    linkopts = ["-pthread"],
    strip_include_prefix = ["includes/Screen"]
)
