cc_library(
    name = "screen",
    srcs = ["Screen.cc"],
    hdrs = ["Screen.h"],
    visibility = ["//visibility:public"],
    linkopts = ["-pthread"],
    copts = ["-Iexternal/libExample/includes/Screen"]
)
